import { SVGProps } from 'react';

export type LogoMarkFlatProps = SVGProps<SVGSVGElement>;

export const LogoMarkFlat = (props: LogoMarkFlatProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192" shapeRendering="crispEdges" role="img" aria-label="Maelstrom-Futurism mark (flat)" {...props}>
        <title>Maelstrom-Futurism</title>
        <rect x="114" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="48" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="48" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="48" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="48" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="48" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="42" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="48" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="54" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="48" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="48" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="48" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="48" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="48" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="36" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="30" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="42" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="48" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="54" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="60" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="144" y="66" width="6" height="6" fill="currentColor"></rect>
        <rect x="144" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="144" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="72" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="144" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="144" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="156" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="162" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="150" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="144" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="78" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="84" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="90" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="96" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="102" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="108" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="114" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="120" width="6" height="6" fill="currentColor"></rect>
        <rect x="138" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="126" width="6" height="6" fill="currentColor"></rect>
        <rect x="132" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="132" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="126" y="144" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="144" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="138" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="144" width="6" height="6" fill="currentColor"></rect>
        <rect x="120" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="114" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="144" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="108" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="144" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="102" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="96" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="90" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="84" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="78" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="72" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="156" width="6" height="6" fill="currentColor"></rect>
        <rect x="66" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="60" y="162" width="6" height="6" fill="currentColor"></rect>
        <rect x="36" y="150" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="144" width="6" height="6" fill="currentColor"></rect>
        <rect x="30" y="138" width="6" height="6" fill="currentColor"></rect>
    </svg>
);

export default LogoMarkFlat;